Homework 3
Kirillov-FN/FedorKirillov_LevelUp pull request #3
Opened 2022-06-23 19:06 UTC by Kirillov-FN

added pom profiles:
Selenium
SeleniumRule
SeleniumDraft
SeleniumDelete

2022-06-24 18:46 UTC, khda91 requested changes
С yahoo конечно вариант хороший, но у меня немного не взлетел :) Просит подтвердить, что я не робот

Исправить замечания

2022-06-24 18:46 UTC, khda91 commented on src/test/java/calculator/CalculatorCosTests.java
> +import calculator.baseclasses.AbstractCalculatorTestBaseClass;
В homework3 должны быть файлы только связанные с homework3. Файлов с домашней раоботой 2 не должно быть в пул реквесте

2022-06-24 18:46 UTC, khda91 commented on src/test/java/selenium/resources/SeleniumTestsResources.java
> +    public void setUp() {
Экземпляр драйвера должен создаваться для каждого теста. В классе может быть несколько тестов

2022-06-24 18:46 UTC, khda91 commented on src/test/java/selenium/sendemail/YahooDeleteTest.java
> +                .cssSelector("div[data-test-id=\"notifications\"]>div>div>div>span>a")));
Можно уменьшить количество переходов вниз по дереву? Любое добавление нового тэга в эту цепочку или удаление из неё приведёт к поломке локатора

2022-06-24 18:46 UTC, khda91 commented on src/test/java/selenium/sendemail/YahooDraftTest.java
> +                        "div[data-test-folder-container=\"Draft\"]>a>span>span[data-test-id=\"displayed-count\"]"));
Можно просто обойтись `div[data-test-folder-container=\"Draft\"] span[data-test-id=\"displayed-count\"]`

2022-06-24 18:46 UTC, khda91 commented on src/test/java/selenium/sendemail/YahooDraftTest.java
> +                .cssSelector("div[data-test-id=\"notifications\"]>div>div>div>span>a")));
Аналогично в классе `src/test/java/selenium/sendemail/YahooDeleteTest.java`

2022-06-24 18:46 UTC, khda91 commented on src/test/java/selenium/sendemail/YahooRuleTest.java
> +                .cssSelector("div[data-test-id=\"notifications\"]>div>div>div>span>a")));
Аналогично в классе `src/test/java/selenium/sendemail/YahooDeleteTest.java`

2022-06-28 19:47 UTC, Kirillov-FN commented on src/test/java/calculator/CalculatorCosTests.java
> +import calculator.baseclasses.AbstractCalculatorTestBaseClass;
Изменения в файлах связаны с переименованием каталогов в ветке homework3.
Убрал эти изменения в этой ветке

2022-06-28 19:47 UTC, Kirillov-FN commented on src/test/java/selenium/resources/SeleniumTestsResources.java
> +    public void setUp() {
fixed

2022-06-28 19:48 UTC, Kirillov-FN commented on src/test/java/selenium/sendemail/YahooDeleteTest.java
> +                .cssSelector("div[data-test-id=\"notifications\"]>div>div>div>span>a")));
fixed

2022-06-28 19:48 UTC, Kirillov-FN commented on src/test/java/selenium/sendemail/YahooDraftTest.java
> +                        "div[data-test-folder-container=\"Draft\"]>a>span>span[data-test-id=\"displayed-count\"]"));
done

2022-06-28 19:48 UTC, Kirillov-FN commented on src/test/java/selenium/sendemail/YahooDraftTest.java
> +                .cssSelector("div[data-test-id=\"notifications\"]>div>div>div>span>a")));
done

2022-06-28 19:49 UTC, Kirillov-FN commented on src/test/java/selenium/sendemail/YahooRuleTest.java
> +                .cssSelector("div[data-test-id=\"notifications\"]>div>div>div>span>a")));
done

2022-06-28 19:56 UTC, Kirillov-FN commented
Запуск прогона можно посмотреть на гифке https://disk.yandex.ru/d/4rCkYRQ7IAVqxA

2022-06-29 15:22 UTC, khda91 approved these changes
работа принята

2022-06-29 15:22 UTC, merged